# Site settings
title: Documentation
email: info@sensetecnic.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains information and updates to the Sense Tecnic
  IoT platform including the WoTKit, FRED and other components.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sensetecnic.github.io" # the base hostname & protocol for your site
twitter_username: sensetecnic
github_username: SenseTecnic

# Build settings
markdown: kramdown
exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.js"

